// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CartFunctionalityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAddToCart() {
    driver.get("https://www.ikea.com/ca/en/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.cssSelector(".hnf-btn--open-menu > .hnf-btn__inner")).click();
    driver.findElement(By.cssSelector(".hnf-menu__nav__main > li:nth-child(1) > .hnf-link")).click();
    driver.findElement(By.linkText("Outdoor")).click();
    driver.findElement(By.linkText("Outdoor furniture")).click();
    driver.findElement(By.cssSelector(".vn-link:nth-child(1) > .vn__nav__title")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vn-link:nth-child(2) > .vn__nav__title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".vn-link:nth-child(3) > .vn__nav__title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".plp-fragment-wrapper:nth-child(2) .pip-aspect-ratio-box:nth-child(2) > .pip-image")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#pip-media-2 .pip-image"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".pip-btn--fluid .pip-btn__label")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".rec-btn--icon-primary-inverse > .rec-btn__inner")).click();
    driver.findElement(By.cssSelector(".js-shopping-cart-icon")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("NÄMMARÖ"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRemoveFromCart() {
    driver.get("https://www.ikea.com/ca/en/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.cssSelector(".hnf-btn--open-menu > .hnf-btn__inner")).click();
    driver.findElement(By.cssSelector(".hnf-menu__nav__main > li:nth-child(1) > .hnf-link")).click();
    driver.findElement(By.linkText("Outdoor")).click();
    driver.findElement(By.linkText("Outdoor furniture")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vn-link:nth-child(2) .hnf-image"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".vn-link:nth-child(2) > .vn__nav__title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".vn-link:nth-child(1) .hnf-image")).click();
    driver.findElement(By.cssSelector(".plp-fragment-wrapper:nth-child(2) .pip-aspect-ratio-box:nth-child(2) > .pip-image")).click();
    driver.findElement(By.cssSelector(".pip-btn--fluid .pip-btn__label")).click();
    driver.findElement(By.cssSelector(".rec-btn--icon-primary-inverse > .rec-btn__inner")).click();
    driver.findElement(By.cssSelector(".js-shopping-cart-icon")).click();
    driver.findElement(By.linkText("Remove product")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rec-carousel-slide:nth-child(2) .pip-aspect-ratio-box:nth-child(2) > .pip-image"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cart-ingka-btn--icon-tertiary-inverse > .cart-ingka-btn__inner")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".noProducts_header__9wz2x"));
      assert(elements.size() > 0);
    }
  }
}
