// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DropdownSortSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSortByMostPopular() {
    driver.get("https://www.ikea.com/ca/en/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    {
      WebElement element = driver.findElement(By.linkText("Best prices"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".hnf-btn--open-menu > .hnf-btn__inner")).click();
    driver.findElement(By.cssSelector(".hnf-menu__nav__main > li:nth-child(1) > .hnf-link")).click();
    driver.findElement(By.linkText("Outdoor")).click();
    driver.findElement(By.linkText("Outdoor furniture")).click();
    driver.findElement(By.cssSelector(".vn-link:nth-child(1) .hnf-image")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vn-link:nth-child(2) > .vn__nav__title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".vn-link:nth-child(1) > .vn__nav__title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".plp-pill:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".plp-radio-button:nth-child(7)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".plp-radio-button:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".plp-pill--active")).click();
  }
  @Test
  public void testSortByPrice() {
    driver.get("https://www.ikea.com/ca/en/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    {
      WebElement element = driver.findElement(By.linkText("Rooms"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Products"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Outdoor")).click();
    driver.findElement(By.linkText("Outdoor furniture")).click();
    driver.findElement(By.cssSelector(".vn-link:nth-child(1) .hnf-image")).click();
    driver.findElement(By.cssSelector(".plp-pill:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".plp-radio-button:nth-child(3)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".plp-radio-button:nth-child(3) > .plp-radio-button__text")).click();
    driver.findElement(By.cssSelector(".plp-filter-information")).click();
  }
}
