// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1ValidLogin() {
    driver.get("https://www.ikea.com/ca/en//ca/en/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    {
      WebElement element = driver.findElement(By.cssSelector(".hnf-location__btn-wrapper--postalcode > .hnf-btn--small .svg-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#hnf-header-postalcodepicker .hnf-nudge-tip .hnf-btn__inner")).click();
    driver.findElement(By.cssSelector("#loyalty-modal-button > .hnf-btn__inner")).click();
    driver.findElement(By.cssSelector("#header__button > .btn__inner")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("boijackie17@gmail.com");
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn--icon-tertiary > .btn__inner"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".btn--icon-tertiary > .btn__inner")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Password_1");
    driver.findElement(By.cssSelector(".btn--emphasised .btn__label")).click();
  }
  @Test
  public void test2InvalidLogin() {
    driver.get("https://www.ikea.com/ca/en/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    {
      WebElement element = driver.findElement(By.cssSelector("#loyalty-modal-button > .hnf-btn__inner"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#loyalty-modal-button > .hnf-btn__inner")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#header__button > .btn__inner")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("jackieboi15@gmail.com");
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn--icon-tertiary > .btn__inner"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".btn--icon-tertiary > .btn__inner"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".input-field--trailing-icon > .input-field__wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".input-field--trailing-icon > .input-field__wrapper")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Password_2");
    driver.findElement(By.cssSelector(".btn--icon-tertiary > .btn__inner")).click();
    driver.findElement(By.cssSelector(".btn--emphasised .btn__label")).click();
    driver.findElement(By.cssSelector(".sc-EHOje")).click();
  }
}
